apiVersion: v1
kind: ReplicationController
metadata:
  name: "my-replication-controller"
spec: 
  selector:
    app: "web"
  template:
    metadata: 
      name: "my-pod"
      labels:
        app: "web"
    spec:
      containers:
        - name: "my-container"
          image: "tomcat"