apiVersion: v1
kind: Pod
metadata: 
  name: "my-db"
  labels:
    app: "database"
spec:
  containers:
    - name: "my-db"
      image: "mysql:5.7"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        - name: MYSQL_DATABASE
          value: redhat
        - name: MYSQL_USER
          value: redhat
        - name: MYSQL_PASSWORD
          value: redhat